Resources:
  BastionHostInstanceSecurityGroupE75D4274:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cdk2Stack/BastionHost/Resource/InstanceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: Name
          Value: BastionHost
      VpcId: vpc-dc0036b8
    Metadata:
      aws:cdk:path: Cdk2Stack/BastionHost/Resource/InstanceSecurityGroup/Resource
  BastionHostInstanceRoleDD3FA5F1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: BastionHost
    Metadata:
      aws:cdk:path: Cdk2Stack/BastionHost/Resource/InstanceRole/Resource
  BastionHostInstanceRoleDefaultPolicy17347525:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ec2messages:*
              - ssm:UpdateInstanceInformation
              - ssmmessages:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: BastionHostInstanceRoleDefaultPolicy17347525
      Roles:
        - Ref: BastionHostInstanceRoleDD3FA5F1
    Metadata:
      aws:cdk:path: Cdk2Stack/BastionHost/Resource/InstanceRole/DefaultPolicy/Resource
  BastionHostInstanceProfile770FCA07:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: BastionHostInstanceRoleDD3FA5F1
    Metadata:
      aws:cdk:path: Cdk2Stack/BastionHost/Resource/InstanceProfile
  BastionHost30F9ED05:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-1a
      BlockDeviceMappings:
        - DeviceName: EBSBastionHost
          Ebs:
            Encrypted: true
            VolumeSize: 10
      IamInstanceProfile:
        Ref: BastionHostInstanceProfile770FCA07
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: t3.nano
      SecurityGroupIds:
        - Fn::GetAtt:
            - BastionHostInstanceSecurityGroupE75D4274
            - GroupId
      SubnetId: subnet-b2985cd5
      Tags:
        - Key: Name
          Value: BastionHost
      UserData:
        Fn::Base64: "#!/bin/bash"
    DependsOn:
      - BastionHostInstanceRoleDefaultPolicy17347525
      - BastionHostInstanceRoleDD3FA5F1
    Metadata:
      aws:cdk:path: Cdk2Stack/BastionHost/Resource/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WOzQrCMBCEn8V7XK2geBQ9qCBY6hOEuMJqmy2bjT+EvLu2Ui+eZhi+GaaAYr6AYrSyjzB259skORaEdFLrbqbCwFEcms3FH6O2UTtXWrENKorZsA8q0fXxAGfTbSV0M0hrG5TY7zjogXx8mv2nYP1n8YQuCulrKxzbrv4XDGg2ZBtIFdf9j15Lrsm9+jM/N/Cl8IVqzDkbz2eEa5jciyVMYTq6BqKxRK/UIFRffQOijcJTAgEAAA==
    Metadata:
      aws:cdk:path: Cdk2Stack/CDKMetadata/Default
Outputs:
  BastionHostBastionHostIdC743CBD6:
    Description: Instance ID of the bastion host. Use this to connect via SSM Session Manager
    Value:
      Ref: BastionHost30F9ED05
Parameters:
  SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

